theme: jekyll-theme-minimal
title: spongalicious
avatar: Photo.jpg
description: Under Construction. Welcome to geocities.

permalink: pretty
gems:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"
