theme: jekyll-theme-merlot
title: wassup wassup wassup
title-img: download.jpeg
description: welcome to wassup wassup wassup. please don't take this seriously, i'm messing around with _config.yml settings
